In [2]:
# index row of two-demensional array
from numpy import array

#define array
data = array([11,22,33,44,55])

# index data
print(data[5])

#0,1,2,3,4 순이니까 5번째는 오류나는게 맞아!

IndexError: index 5 is out of bounds for axis 0 with size 5

In [3]:
#5.4.1
# slice one-dimensional array
from numpy import array

#define array
data = array([11,22,33,44,55])

#index data
print(data[:])

[11 22 33 44 55]


In [4]:
# silce a subset of a one-dimensional array
from numpy import array

#define array
data = array([11,22,33,44,55])

#index data
print(data[0:1])

[11]


In [5]:
#negative slicing of a one-dimensional array
from numpy import array

#define array
data = array([11,22,33,44,55])


#index data
print(data[-2:0])

#엥...다시보기

[]


In [6]:
#split input and output data
from numpy import array

#define array
data = array([
    [11,22,33],
    [44,55,66],
    [77,88,99]])

#separate data
X,y = data[:,:-1], data[:,-1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [7]:
# split train and test data
from numpy import array

#define array
data = array([[11,22,33],[44,55,66],[77,88,99]])

#separate data
split = 2
train,test = data[:split,:], data[split:,:]
print(train)
print(test)


#이것도 뭔가 이상해 다시보기


[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [9]:
#5.5.1
#shape of one-dimensional array
from numpy import array

#define array
data = array([11,22,33,44,55])
print(data.shape)

#괄호 조심하자 괄호 다르면 오류나


(5,)


In [10]:
#shape of two-dimensional array
from numpy import array

#list of data
data = [[11,22],[33,44],[55,66]]

#array of data
data = array(data)
print(data.shape)

(3, 2)


In [12]:
#5.5.2
#reshape 1D array to 2D
from numpy import array

#define array
data = array([11,22,33,44,55])
print(data.shape)

#reshape
data = data.reshape((data.shape[0],1))
print(data.shape)

#반점, 온점 구분 잘 하자 오류나기 딱임!


(5,)
(5, 1)


In [14]:
#reshape 2D array to 3D
from numpy import array

#list of data
data = [[11,22],[33,44],[55,66]]

#array of data
data = array(data)
print(data.shape)

#reshape
data = data.reshape((data.shape[0], data.shape[1],1))
print(data.shape)
print(data)


(3, 2)
(3, 2, 1)
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]


In [15]:
#chapter 6
#6.4.1
#broadcast scalar to one-dimensional array
from numpy import array

#define array
a = array([1,2,3])
print(a)

#define scalar
b = 2
print(b)

#broadcast
c = a+b
print(c)


[1 2 3]
2
[3 4 5]


In [17]:
#broadcast scalar to two-dimensional array
from numpy import array

#define array
A = array([[1,2,3],[1,2,3]])
print(A)

#define scalar
b = 2
print(b)

#broadcast
c = A+b
print(C)

#오류 나는게 맞아!

[[1 2 3]
 [1 2 3]]
2


NameError: name 'C' is not defined

In [18]:
#chapter7
#vector addition
from numpy import array

#define first vector
a = array([1,2,3])
print("a=", a)

#define second vector
b = array([1,2,3])
print("b=", b)

#add vectors
c = a+b
print("a+b=", c)


a= [1 2 3]
b= [1 2 3]
a+b= [2 4 6]


In [19]:
#vector multiplication
from numpy import array

#define first vector
a = array([1,2,3])
print("a=", a)

#define second vector
b = array([1,2,3])
print("b=",b)

#multiple
c = a+b
print("a+b=",c)


a= [1 2 3]
b= [1 2 3]
a+b= [2 4 6]


In [20]:
#chapter 8
#vector L1 norm
from numpy import array
from numpy.linalg import norm #놈을 가져와

#define vector
a = array([1,2,3])
print(a)

#calculate norm
l1 = norm(a,1)
print(l1)


[1 2 3]
6.0


In [22]:
#vector L2 norm
from numpy import array
from numpy.linalg import norm

#define vector
a = array([1,2,3])
print(a)

#calculate norm
l2 = norm(a) #12아님 주의 앞에 알파벳이야
print(l2)


[1 2 3]
3.7416573867739413


In [25]:
#vector max norm
from numpy import inf
from numpy import array
from numpy.linalg import norm

#define vector
a = array([1,2,3])
print(a)

#calculate norm
maxnorm = norm(a, inf) #반점, 온점 주의!
print(maxnorm)


[1 2 3]
3.0
