In [1]:
#create array
from numpy import array

#create array
L = [1.0, 2.0, 3.0]
a = array(L)

#display array
print(a)

#display array shape
print(a.shape)

#display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [3]:
#create empty array

from numpy import empty
a = empty([3,3])
print(a)

[[ 6.17779239e-31 -1.23555848e-30  3.08889620e-31]
 [-1.23555848e-30  2.68733969e-30 -8.34001973e-31]
 [ 3.08889620e-31 -8.34001973e-31  4.78778910e-31]]


In [4]:
#create zero array

from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
#create one array

from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


In [10]:
#create array with vstack
from numpy import array
from numpy import vstack

#create first array
a1 = array([1,2,3])
print("a1 = ",a1)

#create second array
a2 = array([4,5,6])
print("a2 = ",a2)

#vertical stack
a3 = vstack((a1,a2))
print("a3 = ",a3)
print("shape = ",a3.shape)

a1 =  [1 2 3]
a2 =  [4 5 6]
a3 =  [[1 2 3]
 [4 5 6]]
shape =  (2, 3)


In [12]:
#create array with hstack
from numpy import array
from numpy import hstack

#create first array
a1 = array([1,2,3])
print("a1 = ",a1)

#create second array
a2 = array([4,5,6])
print("a2 = ",a2)

#create horizontal stack
a3 = hstack((a1,a2))
print("a3 = ",a3)
print("shape = ", a3.shape)

a1 =  [1 2 3]
a2 =  [4 5 6]
a3 =  [1 2 3 4 5 6]
shape =  (6,)


In [13]:
#create one-dimensional array
from numpy import array

#list of data
data = [11,22,33,44,55]

#arrray of data
data = array(data)
print("data = ", data)
print(type(data))

data =  [11 22 33 44 55]
<class 'numpy.ndarray'>


In [15]:
#create two-dimensional array
from numpy import array

#list of data
data = [[11,22], [33,44], [55,66]]

#array of data
data = array(data)
print("data = ", data)
print(type(data))

data =  [[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [16]:
#index a one-dimensional array
from numpy import array

#define array
data = array([11,22,33,44,55])

#index data
print(data[0])
print(data[4])

11
55


In [18]:
#negative array indexing
from numpy import array

#define array
data = array([11,22,33,44,55])

#index data
print(data[-1])
print(data[-5])

55
11
