In [2]:
#지난 수업 복습 
#vector L1 Norm
from numpy import array
from numpy.linalg import norm

#define vector
a = array([1,2,3])
print(a)

#calculate norm
l1 = norm(a,1)
print(l1)

[1 2 3]
6.0


In [3]:
#CHAPTER 9
#create matrix
from numpy import array
A = array([[1,2,3],[4,5,6]])
print(A)


[[1 2 3]
 [4 5 6]]


In [7]:
#matrix addition
from numpy import array

#define first matrix
A = array([[1,2,3],[4,5,6]])
print(A)

#define second matrix
B = array([[1,2,3],[4,5,6]])
print(B)

#add matrices
C = A + B
print("A+B=",C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
A+B= [[ 2  4  6]
 [ 8 10 12]]


In [6]:
#matrix subtraction
from numpy import array

#define first matrix
A = array([[1,2,3],[4,5,6]])
print(A)

#define second matrix
B = array([[0.5,0.5,0.5],[0.5,0.5,0.5]])
print(B)

#subtract matrices
C = A - B
print("A-B=",C)

[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
A-B= [[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


In [9]:
#matrix Hadamard product 성분끼리 곱
from numpy import array

#define fisrt matrix
A = array([[1,2,3],[4,5,6]])
print(A)

#define second matrix
B = array([[1,2,3],[4,5,6]])
print(B)

#multiply matrices
C = A * B
print("A*B=", C) #print 대문자로 하면 오류남

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
A*B= [[ 1  4  9]
 [16 25 36]]


In [10]:
#matrix division
from numpy import array

#define first matrix
A = array([[1,2,3],[4,5,6]])
print(A)

#define second matrix
B = array([[1,2,3],[4,5,6]])
print(B)

#divide matrices
C = A / B
print("A/B=", C)
# 결과 : 에이랑 비가 같은 컴포넌트이기 떄문에 1

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
A/B= [[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#matrix dot product
from numpy import array

#define first matrix
A = array([[1,2],[3,4],[5,6]])
print(A)

#define second matrix
B = array([[1,2],[3,4]])
print(B)

#multiply matrices
C = A.dot(B)
print(C)

#multiply matrices with @ operator
D = A @ B
print(D)


[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


In [12]:
#matrix-vector multiplication
from numpy import array

#define matrix
A = array([[1,2],[3,4],[5,6]])
print(A)

#define vector
B = array([0.5,0.5])
print(B)

#multiply
C = A.dot(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]


In [15]:
#matrix-scalar multiplication
from numpy import array

#define matrix
A = array([[1,2],[3,4],[5,6]]) #[]사이에 , 잘 찍자 안그러면 오류나
print(A)

#define scalar
b =0.5
print(b)


#multiply
C = A * b
print("A * b = ", C)


[[1 2]
 [3 4]
 [5 6]]
0.5
A * b =  [[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


In [16]:
#CHAPTER 10
#triangular matrices
from numpy import array
from numpy import tril
from numpy import triu

#define square matrix
M = array([[1,2,3],[1,2,3],[1,2,3]])
print(M)

#lower triangular matrix
lower = tril(M)
print(lower)

#upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [17]:
#diagonal matrix
from numpy import array
from numpy import diag

#define square matrix
M = array([[1,2,3],[1,2,3],[1,2,3]])
print(M)

#extract diagonal vector
d = diag(M)
print(d)

#create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [18]:
#identity matrix 항등행렬 (곱해도 변화시키지 않아)
from numpy import identity
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#orthogonal matrix
from numpy import array
from numpy.linalg import inv #inv 오타 주의

#define orthogonal matrix
Q = array([[1,0],[0,-1]])
print(Q)

#inverse equivalence
V = inv(Q)
print(Q.T)
print(V)

#identity equivalence
I = Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]
